-- ============================================================
-- Seed: treatment_guidelines
-- ============================================================
-- Auto-generated from ml/treatment_recommendations.py to keep the
-- Python pipeline (used for the ML side / testing) and the
-- Supabase DB (used by the Flutter app) in sync. Regenerate this
-- file whenever treatment_recommendations.py changes, rather than
-- editing it by hand, to avoid the two drifting apart.
-- Run this AFTER supabase_schema.sql.

insert into public.treatment_guidelines (disease_name, severity_stage, recommendation, prevention_tips) values
('Tomato___healthy', 'G0', 'No treatment needed. Plant is healthy.', 'Continue regular monitoring, proper spacing, and balanced fertilization.'),
('Tomato___Early_blight', 'G1', 'Remove affected lower leaves. Apply a preventive copper-based fungicide.', 'Mulch soil to prevent spore splash-back onto leaves.'),
('Tomato___Early_blight', 'G2', 'Apply copper-based or chlorothalonil fungicide every 7-10 days. Remove and destroy affected leaves.', 'Rotate crops annually; avoid planting tomatoes/potatoes in the same soil consecutively.'),
('Tomato___Early_blight', 'G3', 'Apply systemic fungicide immediately. Remove severely affected plants to prevent spread. Consult local agricultural extension officer.', 'Consider resistant tomato varieties for the next planting cycle.'),
('Tomato___Late_blight', 'G1', 'Apply preventive fungicide (mancozeb or copper-based).', 'Improve field drainage and airflow between plants.'),
('Tomato___Late_blight', 'G2', 'Apply systemic fungicide (metalaxyl-based). Remove infected foliage immediately.', 'Avoid working in fields when foliage is wet to reduce spread.'),
('Tomato___Late_blight', 'G3', 'Urgent: remove and destroy infected plants entirely. Apply fungicide to remaining healthy plants as a barrier.', 'Late blight can destroy a field within days - report to local agri-extension for regional alerts.'),
('Tomato___Bacterial_spot', 'G1', 'Apply copper-based bactericide. Avoid handling wet plants.', 'Use certified disease-free seeds/transplants.'),
('Tomato___Bacterial_spot', 'G2', 'Increase copper spray frequency to every 5-7 days. Remove severely spotted leaves.', 'Avoid overhead irrigation; water at the base of plants.'),
('Tomato___Bacterial_spot', 'G3', 'Remove and destroy heavily infected plants. Apply bactericide to remaining crop.', 'Rotate with non-solanaceous crops for at least 2 years.'),
('Tomato___Leaf_Mold', 'G1', 'Improve greenhouse/field ventilation. Apply fungicide if humidity remains high.', 'Reduce humidity around plants; increase plant spacing.'),
('Tomato___Leaf_Mold', 'G2', 'Apply fungicide (chlorothalonil or copper-based). Remove affected leaves.', 'Avoid leaf wetness overnight - water early in the day.'),
('Tomato___Leaf_Mold', 'G3', 'Apply systemic fungicide immediately; heavy leaf mold can severely reduce yield.', 'Use resistant tomato varieties in humid climates.'),
('Tomato___Septoria_leaf_spot', 'G1', 'Remove lower affected leaves. Apply preventive fungicide.', 'Mulch to prevent soil splash onto lower leaves.'),
('Tomato___Septoria_leaf_spot', 'G2', 'Apply fungicide every 7-10 days. Remove and destroy infected debris.', 'Avoid working among wet plants to prevent spread.'),
('Tomato___Septoria_leaf_spot', 'G3', 'Apply fungicide immediately; consider removing severely defoliated plants.', 'Practice 2-3 year crop rotation away from tomato/potato.'),
('Tomato___Spider_mites Two-spotted_spider_mite', 'G1', 'Spray with insecticidal soap or neem oil.', 'Keep plants well-watered - mites thrive in drought-stressed plants.'),
('Tomato___Spider_mites Two-spotted_spider_mite', 'G2', 'Apply miticide. Introduce predatory mites if using biological control.', 'Avoid excessive nitrogen fertilization, which favors mite reproduction.'),
('Tomato___Spider_mites Two-spotted_spider_mite', 'G3', 'Apply targeted miticide immediately; heavy infestation can defoliate plants rapidly.', 'Regularly inspect undersides of leaves for early detection.'),
('Tomato___Target_Spot', 'G1', 'Apply preventive fungicide; remove affected leaves.', 'Ensure good air circulation between plants.'),
('Tomato___Target_Spot', 'G2', 'Apply fungicide (azoxystrobin or chlorothalonil-based) every 7-10 days.', 'Avoid overhead watering; remove crop debris after harvest.'),
('Tomato___Target_Spot', 'G3', 'Apply fungicide immediately and remove severely infected plant material.', 'Rotate crops and avoid dense planting in future seasons.'),
('Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'G1', 'Control whitefly vectors with insecticidal soap; remove affected leaves.', 'Use whitefly-proof netting/screens in nursery stage.'),
('Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'G2', 'Apply systemic insecticide to control whitefly population. Remove heavily symptomatic plants.', 'Use reflective mulches to repel whiteflies.'),
('Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'G3', 'Remove and destroy severely infected plants immediately - no cure exists once systemic. Focus on protecting remaining crop from whiteflies.', 'Plant virus-resistant tomato varieties in future seasons.'),
('Tomato___Tomato_mosaic_virus', 'G1', 'Remove affected leaves; disinfect tools between plants (virus spreads via contact).', 'Wash hands and tools with soap before handling plants.'),
('Tomato___Tomato_mosaic_virus', 'G2', 'Remove moderately affected plants if spread is increasing. No chemical cure exists.', 'Avoid tobacco product use near plants (a known transmission source).'),
('Tomato___Tomato_mosaic_virus', 'G3', 'Remove and destroy severely infected plants to protect the rest of the field.', 'Use certified virus-free seed for future planting.'),
('Potato___healthy', 'G0', 'No treatment needed. Plant is healthy.', 'Continue regular monitoring and good field hygiene.'),
('Potato___Early_blight', 'G1', 'Apply preventive fungicide. Remove lower affected leaves.', 'Ensure balanced fertilization - avoid nitrogen deficiency, which increases susceptibility.'),
('Potato___Early_blight', 'G2', 'Apply fungicide (chlorothalonil or mancozeb) every 7-10 days.', 'Rotate with non-host crops for at least 2 years.'),
('Potato___Early_blight', 'G3', 'Apply fungicide immediately; consider early harvest if tuber bulking is complete.', 'Use certified disease-free seed potatoes.'),
('Potato___Late_blight', 'G1', 'Apply preventive fungicide immediately - late blight spreads extremely fast.', 'Monitor weather forecasts; blight thrives in cool, wet conditions.'),
('Potato___Late_blight', 'G2', 'Apply systemic fungicide. Remove and destroy infected foliage.', 'Improve field drainage and plant spacing for airflow.'),
('Potato___Late_blight', 'G3', 'Urgent: destroy infected plants to prevent field-wide loss. This disease caused historic famines - treat as emergency.', 'Report outbreaks to local agricultural extension for regional monitoring.'),
('Apple___healthy', 'G0', 'No treatment needed.', 'Prune trees to improve air circulation.'),
('Apple___Black_rot', 'G1', 'Remove mummified fruit and cankers from tree.', 'Sanitize pruning tools between cuts.'),
('Apple___Black_rot', 'G2', 'Apply fungicide spray program (captan or myclobutanil-based) during growing season.', 'Remove nearby wild/abandoned apple trees that can host the fungus.'),
('Apple___Black_rot', 'G3', 'Aggressive pruning of infected branches. Apply fungicide immediately.', 'Consider resistant apple cultivars for future plantings.'),
('Apple___Apple_scab', 'G1', 'Apply preventive fungicide at green-tip stage.', 'Rake and destroy fallen leaves in autumn (fungus overwinters there).'),
('Apple___Apple_scab', 'G2', 'Apply fungicide (myclobutanil or captan) every 7-14 days through the season.', 'Prune for better air circulation and sunlight penetration.'),
('Apple___Apple_scab', 'G3', 'Apply fungicide immediately; heavy defoliation risk affects fruit yield next season too.', 'Plant scab-resistant apple varieties.'),
('Apple___Cedar_apple_rust', 'G1', 'Apply preventive fungicide in spring when orange gall spores are active nearby.', 'Remove nearby juniper/cedar trees within 2 miles if feasible (alternate host).'),
('Apple___Cedar_apple_rust', 'G2', 'Apply fungicide (myclobutanil-based) every 10-14 days during spring.', 'Choose rust-resistant apple varieties for new plantings.'),
('Apple___Cedar_apple_rust', 'G3', 'Apply fungicide immediately and remove heavily infected leaves.', 'Coordinate with neighbors to remove alternate juniper hosts in the area.'),
('Corn___healthy', 'G0', 'No treatment needed.', 'Practice crop rotation with non-host crops.'),
('Corn___Northern_Leaf_Blight', 'G1', 'Monitor closely; apply fungicide if weather remains humid.', 'Use resistant hybrid seed varieties where available.'),
('Corn___Northern_Leaf_Blight', 'G2', 'Apply foliar fungicide (strobilurin or triazole-based).', 'Till under crop residue after harvest to reduce fungal spores.'),
('Corn___Northern_Leaf_Blight', 'G3', 'Apply fungicide immediately; yield loss risk is high at this stage.', 'Rotate to soybean or other non-host crop next season.'),
('Corn___Common_rust', 'G1', 'Monitor; fungicide rarely needed at this stage for resistant hybrids.', 'Plant rust-resistant hybrids where common rust pressure is high.'),
('Corn___Common_rust', 'G2', 'Apply fungicide if susceptible hybrid and conditions favor spread.', 'Avoid late planting that exposes young plants to peak rust season.'),
('Corn___Common_rust', 'G3', 'Apply fungicide immediately to protect remaining green leaf area for grain fill.', 'Select resistant hybrids for future seasons in high-pressure areas.'),
('Corn___Cercospora_leaf_spot Gray_leaf_spot', 'G1', 'Monitor; consider fungicide if continuous corn planting history.', 'Rotate crops; avoid continuous corn-on-corn planting.'),
('Corn___Cercospora_leaf_spot Gray_leaf_spot', 'G2', 'Apply foliar fungicide, especially before tasseling.', 'Till crop residue to reduce overwintering fungal spores.'),
('Corn___Cercospora_leaf_spot Gray_leaf_spot', 'G3', 'Apply fungicide immediately; significant yield loss risk from leaf area loss.', 'Select resistant hybrids and rotate away from corn for a season.'),
('Grape___healthy', 'G0', 'No treatment needed.', 'Maintain good canopy management for airflow.'),
('Grape___Black_rot', 'G1', 'Remove mummified berries and infected leaves.', 'Prune for open canopy to reduce humidity around clusters.'),
('Grape___Black_rot', 'G2', 'Apply fungicide (myclobutanil or captan) starting at bloom.', 'Remove wild grape vines nearby that can harbor the fungus.'),
('Grape___Black_rot', 'G3', 'Apply fungicide immediately and remove severely infected clusters.', 'Consider resistant grape varieties for new plantings.'),
('Grape___Esca_(Black_Measles)', 'G1', 'Prune out affected wood during dry weather; disinfect tools.', 'Avoid pruning wounds during wet weather when fungal spores are active.'),
('Grape___Esca_(Black_Measles)', 'G2', 'Remove and destroy affected canes/spurs. No effective fungicide cure exists.', 'Protect large pruning wounds with wound sealant.'),
('Grape___Esca_(Black_Measles)', 'G3', 'Remove severely affected vines to prevent spread to healthy vines.', 'Replant with certified disease-free nursery stock.'),
('Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'G1', 'Apply preventive fungicide; remove affected leaves.', 'Improve canopy airflow through leaf pulling.'),
('Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'G2', 'Apply fungicide (copper-based) every 10-14 days.', 'Avoid overhead irrigation.'),
('Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'G3', 'Apply fungicide immediately; heavy defoliation affects fruit ripening.', 'Rotate fungicide classes to avoid resistance buildup.')
on conflict (disease_name, severity_stage) do nothing;
